title: "Nehal C. P."
description: "Astrophysics Researcher | Galaxy Evolution & AGN"
url: "https://ncp00.github.io"
baseurl: ""
lang: "en"
markdown: kramdown
permalink: /notes/:title/
plugins: []
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
